server:
  port: 8190

spring:
  application:
    name: store-search
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false
  redis:
    host: 192.168.80.3
    port: 6379