server:
  port: 8180

spring:
  application:
    name: store-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.104:8848
    alicloud:
      access-key: 自己的阿里云
      secret-key: 自己的阿里云
      oss:
        endpoint: 自己的阿里云
        bucket: 自己的阿里云